services:
  # Servicio de la Aplicación NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindconnect-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Conexión a la BD (usando el nombre del servicio 'db' como host)
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mindconnect_db
      # Otras variables (Copia las de tu .env local si es necesario)
      - JWT_SECRET=secreto_para_desarrollo_local
      # Configura estas si vas a probar el envío de correos o IA desde el contenedor
      # - MAIL_USER=...
      # - MAIL_PASS=...
    depends_on:
      - db
    networks:
      - mindconnect-network

  # Servicio de Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: mindconnect-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mindconnect_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mindconnect-network

# Volúmenes persistentes
volumes:
  postgres_data:

# Redes
networks:
  mindconnect-network:
    driver: bridge


