services:
  # Servicio de la Aplicación NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindconnect-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Conexión a la BD (usando el nombre del servicio 'db' como host)
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mindconnect_db
      # Otras variables (Copia las de tu .env local si es necesario)
      - JWT_SECRET=secreto_para_desarrollo_local
      # Configura estas si vas a probar el envío de correos o IA desde el contenedor
      # IMPORTANTE: Para que funcione el "Olvidé mi contraseña", configura estas variables:
      - MAIL_USER=epescaalfonso@gmail.com
      - MAIL_PASS=csza ygjo xdgu pbed
      - MAIL_FROM="Soporte Salud Mental <erika.pesca@gmail.com>"
      # Si no las configuras, verás un error "Internal server error" al intentar recuperar contraseña
      # Configuración de IA (Groq)
      # IMPORTANTE: Agrega tu GROQ_API_KEY aquí para usar respuestas de IA avanzadas
      # Obtén tu API key en: https://console.groq.com/
      - GROQ_API_KEY=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
    depends_on:
      - db
    networks:
      - mindconnect-network

  # Servicio de Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: mindconnect-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mindconnect_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mindconnect-network

# Volúmenes persistentes
volumes:
  postgres_data:

# Redes
networks:
  mindconnect-network:
    driver: bridge


